/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CCameraBox: typeof import('./src/components/CCameraBox.vue')['default']
    CElectricField: typeof import('./src/components/CElectricField.vue')['default']
    CLoader: typeof import('./src/components/CLoader.vue')['default']
    CMagneticField: typeof import('./src/components/CMagneticField.vue')['default']
    CParticleTrajectory: typeof import('./src/components/CParticleTrajectory.vue')['default']
    CSwitch: typeof import('./src/components/CSwitch.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElRange: typeof import('element-plus/es')['ElRange']
    ElSlider: typeof import('element-plus/es')['ElSlider']
  }
}
